### ISSUE TITLE
SIA ZGM Arsenals Opfor 3CB Takistan Insurgents

### ISSUE THREAD

**Issue by SilentNM-SIA** [Soliders-in-Arms-Arma-3-Group/arsenals#53]
3CB Takistan Insurgents | taki_insurgents
-- | --

**Comment by L-McKendrick** [comment]
Fixed: https://github.com/Soliders-in-Arms-Arma-3-Group/arsenals/blob/1ac217305b68695ce77e5148fc64ab1748c44a19/taki_insurgents.txt
